
map:
    resource: "@MapBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

article:
    resource: "@ArticleBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /user

app:
    resource: '@AppBundle/Controller/'
    type: annotation


