<?php

namespace ArticleBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByCategoryAndOrderByName($categories)
    {
    return $this->createQueryBuilder('a')
        ->where('a.categories = :categories')
        ->setParameter('categories', $categories)
        ->orderBy('a.misAJourLe', 'ASC')
        ->getQuery()
        ->getResult()
    ;
    }   
}
