<?php

namespace ArticleBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{

    public function categorieQueryBuilder(){

        return $this->createQueryBuilder('a')
            ->join('a.categorie', 'c')
            ->addSelect('c')
            ->where('a.id = :id')
            ->setParameter('id', $article);
    }
}
